# config
switch: true

list:
  - 'system_mini'
  - 'EndlessPixel'
  - 'Modpack'
  - 'Minecraft'
  - 'Java'
edition_list:
  - '1.21.4': "v5"
  - '1.21.6': "v6"
  - '1.21.8': "v7"
  - '1.21.9': "v8"
  # Up
  
metadata: "data"

version: 1

# I don't know what to write.
