name: Crash
description: Game Crashes or Freezes
title: "[Crash] "
labels:
  - bug
  - crash

body:
  - type: checkboxes
    id: pre-check
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have checked the issues and FAQ and confirmed that this problem has never been submitted before.
          required: true
  - type: markdown
    attributes:
      value: "Please describe the crash..."
      placeholder: "Please describe the crash..."
    validations:
      required: true