name: Request
description: New Features and Requests
title: "[Request] "
labels:
  - enhancement

body:
  - type: markdown
    attributes:
      value: "Please describe the request..."
      placeholder: "Please describe the request..."
    validations:
      required: true
